### ISSUE TITLE
Wrong paper link

### ISSUE THREAD

**Issue by Mahelita** [TNTLFreiburg/braindecode-modules#2]
https://github.com/TNTLFreiburg/braindecode-modules/blob/master/online/README.md
The linked paper is not using any online decoding.
You probably meant to link
https://www.sciencedirect.com/science/article/pii/S0921889018302227
and possibly
https://ieeexplore.ieee.org/abstract/document/8098658
But these used the legacy code (theano+lasagne) which lead to the linked code (pytorch).

**Comment by gemeinl** [comment]
You are right, thanks for pointing this out. I added the two papers. Could you please verify that the linking is correct now?

**Comment by Mahelita** [comment]
Thanks!
